#Website	Apple.com
#Apple Inc., formerly Apple Computer, Inc., is an American multinational corporation headquartered in Cupertino, California[2] that designs, develops, and sells consumer electronics, computer software and personal computers. Its best-known hardware products are the Mac line of computers, the iPod music player, the iPhone smartphone, and the iPad tablet computer. Its consumer software includes the OS X and iOS operating systems, the iTunes media browser, the Safari web browser, and the iLife and iWork creativity and productivity suites.
#The company was founded on April 1, 1976, and incorporated as Apple Computer, Inc. on January 3, 1977.[6] The word "Computer" was removed from its name on January 9, 2007, the same day Steve Jobs introduced the iPhone, reflecting its shifted focus towards consumer electronics.[7][8][9]
#Apple is the world's second-largest information technology company by revenue after Samsung Electronics, and the world's third-largest mobile phone maker after Samsung and Nokia.[10] Fortune magazine named Apple the most admired company in the United States in 2008, and in the world from 2008 to 2012.[11][12][13][14][15] However, the company has received criticism for its contractors' labor practices, and for Apple's own environmental and business practices.[16][17][18]
#As of May 2013, Apple maintains 408 retail stores in fourteen countries[19][20] as well as the online Apple Store and iTunes Store,[21] the latter of which is the world's largest music retailer.[22] Apple is the largest publicly traded corporation in the world by market capitalization, with an estimated value of US$415 billion as of March 2013. As of Sept 29 2012, the company had 72,800 permanent full-time employees and 3,300 temporary full-time employees worldwide.[4] Its worldwide annual revenue in 2012 totalled $156 billion.[4] In May 2013, Apple entered the top ten of the Fortune 500 list of companies for the first time, rising 11 places above its 2012 ranking to take the sixth position.[23]
#The Apple I, Apple's first product, was sold as an assembled circuit board and lacked basic features such as a keyboard, monitor, and case. The owner of this unit added a keyboard and a wooden case.
#Apple was established on April 1, 1976, by Steve Jobs, Steve Wozniak and Ronald Wayne[1] to sell the Apple I personal computer kit, a computer single handedly designed by Wozniak. The kits were hand-built by Wozniak[24][25] and first shown to the public at the Homebrew Computer Club.[26] The Apple I was sold as a motherboard (with CPU, RAM, and basic textual-video chips), which is less than what is today considered a complete personal computer.[27] The Apple I went on sale in July 1976 and was market-priced at $666.66 ($2,690 in 2013 dollars, adjusted for inflation).[28][29][30][31][32][33]
#Apple was incorporated January 3, 1977,[6] without Wayne, who sold his share of the company back to Jobs and Wozniak for $800. Multi-millionaire Mike Markkula provided essential business expertise and funding of $250,000 during the incorporation of Apple.[34][35]
#During the first five years of operations, revenues doubled every four months, an average growth rate of 700%.
#The Apple II, also invented by Wozniak, was introduced on April 16, 1977, at the first West Coast Computer Faire. It differed from its major rivals, the TRS-80 and Commodore PET, due to its character cell-based color graphics and an open architecture. While early models used ordinary cassette tapes as storage devices, they were superseded by the introduction of a 5 1/4 inch floppy disk drive and interface, the Disk II.[36]
#The Apple II was chosen to be the desktop platform for the first "killer app" of the business world, VisiCalc, a spreadsheet program.[37] VisiCalc created a business market for the Apple II and gave home users compatibility with the office, an additional reason to buy an Apple II.[37] Apple was a distant third place to Commodore and Tandy until VisiCalc came along.[38][39]
#By the end of the 1970s, Apple had a staff of computer designers and a production line. The company introduced the Apple III in May 1980 in an attempt to compete with IBM and Microsoft in the business and corporate computing market.[40]
#Jobs and several Apple employees, including Jef Raskin, visited Xerox PARC in December 1979 to see the Xerox Alto. Xerox granted Apple engineers three days of access to the PARC facilities in return for the option to buy 100,000 shares (800,000 split-adjusted shares) of Apple at the pre-IPO price of $10 a share.[41] Jobs was immediately convinced that all future computers would use a graphical user interface (GUI), and development of a GUI began for the Apple Lisa.[42]
#On December 12, 1980, Apple went public at $22 per share,[43] generating more capital than any IPO since Ford Motor Company in 1956 and instantly creating more millionaires (about 300) than any company in history.[44]
#Apple's "1984" television ad, set in a dystopian future modeled after the George Orwell novel Nineteen Eighty-Four, set the tone for the introduction of the Macintosh.
#Apple began working on the Apple Lisa in 1978. In 1982, Jobs was pushed from the Lisa team due to infighting. Jobs took over Jef Raskin's low-cost-computer project, the Macintosh. A race broke out between the Lisa team and the Macintosh team over which product would ship first. Lisa won the race in 1983 and became the first personal computer sold to the public with a GUI, but was a commercial failure due to its high price tag and limited software titles.[45]
#The first Macintosh, released in 1984
#In 1984, Apple next launched the Macintosh. Its debut was announced by the now famous $1.5 million television commercial "1984". It was directed by Ridley Scott and was aired during the third quarter of Super Bowl XVIII on January 22, 1984.[46] It is now hailed as a watershed event for Apple's success[47] and a "masterpiece".[48][49]
#See also: Timeline of Apple II family and Timeline of Macintosh models
#The Macintosh Portable was Apple's first "portable" Macintosh computer, released in 1989.
#The Macintosh Portable was introduced in 1989 and was designed to be just as powerful as a desktop Macintosh, but weighed a bulky 7.5 kilograms (17 lb) with a 12-hour battery life. After the Macintosh Portable, Apple introduced the PowerBook in 1991. The same year, Apple introduced System 7, a major upgrade to the operating system which added color to the interface and introduced new networking capabilities. It remained the architectural basis for Mac OS until 2001.
#The success of the PowerBook and other products brought increasing revenue.[53] For some time, Apple was doing incredibly well, introducing fresh new products and generating increasing profits in the process. The magazine MacAddict named the period between 1989 and 1991 as the "first golden age" of the Macintosh.
#Following the success of the Macintosh LC, Apple introduced the Centris line, a low-end Quadra, and the ill-fated Performa line that was sold with an overwhelming number of configurations and software bundles to avoid competing with the various consumer outlets such as Sears, Price Club, and Wal-Mart (the primary dealers for these models). Consumers ended up confused and did not understand the difference between models.[55]
# this time Apple experimented with a number of other failed consumer targeted products including digital cameras, portable CD audio players, speakers, video consoles, and TV appliances. Enormous resources were also invested in the problem-plagued Newton division based on John Sculley's unrealistic market forecasts.[citation needed] Ultimately, none of these products helped, as Apple's market share and stock prices continued to slide.[citation needed]
#Apple saw the Apple II series as too expensive to produce, while taking away sales from the low end Macintosh.[56] In 1990, Apple released the Macintosh LC with a single expansion slot for the Apple IIe Card to migrate Apple II users to the Macintosh platform.[56] Apple stopped selling the Apple IIe in 1993.
#Microsoft continued to gain market share with Windows focusing on delivering software to cheap commodity personal computers while Apple was delivering a richly engineered, but expensive, experience.[57] Apple relied on high profit margins and never developed a clear response. Instead, they sued Microsoft for using a graphical user interface similar to the Apple Lisa in Apple Computer, Inc. v. Microsoft Corporation.[58] The lawsuit dragged on for years before it was finally dismissed. At the same time, a series of major product flops and missed deadlines sullied Apple's reputation, and Sculley was replaced as CEO by Michael Spindler.[59]
#The Newton was Apple's first foray into the PDA markets, as well as one of the first in the industry. Despite being a financial flop at the time of its release, it helped pave the way for the Palm Pilot and Apple's own iPhone and iPad in the future.
# the early 1990s, Apple was developing alternative platforms to the Macintosh, such as the A/UX. Apple had also begun to experiment in providing a Mac-only online portal which they called eWorld, developed in collaboration with America Online and designed as a Mac-friendly alternative to other online services such as CompuServe. The Macintosh platform was itself becoming outdated because it was not built for multitasking, and several important software routines were programmed directly into the hardware. In addition, Apple was facing competition from OS/2 and UNIX vendors such as Sun Microsystems. The Macintosh would need to be replaced by a new platform, or reworked to run on more powerful hardware.[60]
#In 1994, Apple allied with IBM and Motorola in the AIM alliance. The goal was to create a new computing platform (the PowerPC Reference Platform), which would use IBM and Motorola hardware coupled with Apple's software. The AIM alliance hoped that PReP's performance and Apple's software would leave the PC far behind, thus countering Microsoft. The same year, Apple introduced the Power Macintosh, the first of many Apple computers to use Motorola's PowerPC processor.[61]
#In 1996, Michael Spindler was replaced by Gil Amelio as CEO. Gil Amelio made many changes at Apple, including extensive layoffs.[62] After numerous failed attempts to improve Mac OS, first with the Taligent project, then later with Copland and Gershwin, Amelio chose to purchase NeXT and its NeXTSTEP operating system, bringing Steve Jobs back to Apple as an advisor.[63] On July 9, 1997, Gil Amelio was ousted by the board of directors after overseeing a three-year record-low stock price and crippling financial losses. Jobs became the interim CEO and began restructuring the company's product line.
#At the 1997 Macworld Expo, Steve Jobs announced that Apple would join Microsoft to release new versions of Microsoft Office for the Macintosh, and that Microsoft made a $150 million investment in non-voting Apple stock.[64]
#WOn November 10, 1997, Apple introduced the Apple Online Store, tied to a new build-to-order manufacturing strategy.[65][66]
#On August 15, 1998, Apple introduced a new all-in-one computer reminiscent of the Macintosh 128K: the iMac. The iMac design team was led by Jonathan Ive, who would later design the iPod and the iPhone.[67][68] The iMac featured modern technology and a unique design, and sold almost 800,000 units in its first five months.[69]
#Through this period, Apple purchased several companies to create a portfolio of professional and consumer-oriented digital production software. In 1998, Apple announced the purchase of Macromedia's Final Cut software, signaling its expansion into the digital video editing market.[70] The following year, Apple released two video editing products: iMovie for consumers and, for professionals, Final Cut Pro, which has gone on to be a significant video-editing program, with 800,000 registered users in early 2007.[71] In 2002, Apple purchased Nothing Real for their advanced digital compositing application Shake,[72] as well as Emagic for their music productivity application Logic, which led to the development of their consumer-level GarageBand application.[73][74] iPhoto's release the same year completed the iLife suite.[75]
#Apple retail stores allow potential customers to use floor models without making a purchase.
#(Apple Store, North Michigan Avenue, Chicago, Illinois in 2005)
#3On May 19, 2001, Apple opened the first official Apple Retail Stores in Virginia and California.[77] On July 9, they bought Spruce Technologies, a DVD authoring company. On October 23 of the same year, Apple announced the iPod portable digital audio player, and started selling it on November 10. The product was phenomenally successful — over 100 million units were sold within six years.[78][79] In 2003, Apple's iTunes Store was introduced, offering online music downloads for $0.99 a song and integration with the iPod. The service quickly became the market leader in online music services, with over 5 billion downloads by June 19, 2008.[80]
#Since 2001, Apple's design team has progressively abandoned the use of translucent colored plastics first used in the iMac G3. This began with the titanium PowerBook and was followed by the white polycarbonate iBook and the flat-panel iMac.[81][82]
#The MacBook Pro, Apple's first laptop with an Intel microprocessor, announced in January 2006.
#At the Worldwide Developers Conference keynote address on June 6, 2005, Steve Jobs announced that Apple would begin producing Intel-based Mac computers in 2006.[83] On January 10, 2006, the new MacBook Pro and iMac became the first Apple computers to use Intel's Core Duo CPU. By August 7, 2006 Apple had transitioned the entire Mac product line to Intel chips, over one year sooner than announced.[83] The Power Mac, iBook, and PowerBook brands were retired during the transition; the Mac Pro, MacBook, and MacBook Pro became their respective successors.[84][85] On April 29, 2009, The Wall Street Journal reported that Apple was building its own team of engineers to design microchips.[86]
#Apple introduced Boot Camp to help users install Windows XP or Windows Vista on their Intel Macs alongside Mac OS X.[87]
#Apple's success during this period was evident in its stock price. Between early 2003 and 2006, the price of Apple's stock increased more than tenfold, from around $6 per share (split-adjusted) to over $80. In January 2006, Apple's market cap surpassed that of Dell.[88] Nine years prior, Dell's CEO Michael Dell said that if he ran Apple he would "shut it down and give the money back to the shareholders."[89] Although Apple's market share in computers had grown, it remained far behind competitors using Microsoft Windows, with only about 8% of desktops and laptops in the US.[citation needed]
#Apple achieved widespread success with its iPhone, iPod Touch and iPad products, which introduced innovations in mobile phones, portable music players and personal computers respectively. In addition, the implementation of a store for the purchase of software applications represented a new business model. Touch screens had been invented and seen in mobile devices before, but Apple was the first to achieve mass market adoption of such a user interface that included particular pre-programmed touch gestures.
#Delivering his keynote speech at the Macworld Expo on January 9, 2007, Jobs announced that Apple Computer, Inc. would from that point on be known as Apple Inc., because computers were no longer the main focus of the company, which had shifted its emphasis to mobile electronic devices. The event also saw the announcement of the iPhone and the Apple TV.[90] The following day, Apple shares hit $97.80, an all-time high at that point. In May, Apple's share price passed the $100 mark.[91]
#In an article posted on Apple's website on February 6, 2007, Steve Jobs wrote that Apple would be willing to sell music on the iTunes Store without digital rights management (DRM) (which would allow tracks to be played on third-party players), if record labels would agree to drop the technology.[92] On April 2, 2007, Apple and EMI jointly announced the removal of DRM technology from EMI's catalog in the iTunes Store, effective in May.[93] Other record labels followed later that year.
#In July of the following year, Apple launched the App Store to sell third-party applications for the iPhone and iPod Touch.[94] Within a month, the store sold 60 million applications and brought in $1 million daily on average, with Jobs speculating that the App Store could become a billion-dollar business for Apple.[95] Three months later, it was announced that Apple had become the third-largest mobile handset supplier in the world due to the popularity of the iPhone.[96]
#On December 16, 2008, Apple announced that after over 20 years of attending Macworld, 2009 would be the last year Apple would be attending the Macworld Expo, and that Phil Schiller would deliver the 2009 keynote in lieu of the expected Jobs.[97] Almost exactly one month later, on January 14, 2009, an internal Apple memo from Jobs announced that he would be taking a six-month leave of absence, until the end of June 2009, to allow him to better focus on his health and to allow the company to better focus on its products without having the rampant media speculating about his health.[98] Despite Jobs' absence, Apple recorded its best non-holiday quarter (Q1 FY 2009) during the recession with a revenue of $8.16 billion and a profit of $1.21 billion.[99][100]
#Apple unveils iPhone 4, iOS 4 at Worldwide Developers Conference 2010
#Apple to give free cases, refunds to iPhone 4 owners
#Apple unveils new iPods, Apple TV; updates iOS, iTunes
####In October 2010, Apple shares hit an all-time high, eclipsing $300.[106] Additionally, on October 20, Apple updated their MacBook Air laptop, iLife suite of applications, and unveiled Mac OS X Lion, the last version with the name Mac OS X.[107] On January 6, 2011, the company opened their Mac App Store, a digital software distribution platform, similar to the existing iOS App Store.[108] Apple was featured in the documentary Something Ventured which premiered in 2011.
#On January 17, 2011, Jobs announced in an internal Apple memo that he would take another medical leave of absence, for an indefinite period, to allow him to focus on his health. Chief operating officer Tim Cook assumed Jobs' day-to-day operations at Apple, although Jobs would still remain "involved in major strategic decisions for the company."[109] Apple became the most valuable consumer-facing brand in the world.[110] In June 2011, Steve Jobs surprisingly took the stage and unveiled iCloud, an online storage and syncing service for music, photos, files and software which replaced MobileMe, Apple's previous attempt at content syncing.[111]
#This would be the last product launch Jobs would attend before his death. It has been argued that Apple has achieved such efficiency in its supply chain[112] that the company operates as a monopsony (one buyer, many sellers), in that it can dictate terms to its suppliers.[113][114] In July 2011, due to the American debt-ceiling crisis, Apple's financial reserves were briefly larger than those of the U.S. Government.[115]
#On August 24, 2011, Jobs resigned his position as CEO of Apple.[116] He was replaced by Tim Cook and Jobs became Apple's chairman. Prior to this, Apple did not have a chairman and instead had two co-lead directors, Andrea Jung and Arthur D. Levinson, who continued with those titles until Levinson became Chairman of the Board in November.[117]
#On October 4, 2011, Apple announced the iPhone 4S, which included an improved camera with 1080p video recording, a dual core A5 chip capable of 7 times faster graphics than the A4, an "intelligent software assistant" named Siri, and cloud-sourced data with iCloud.[118][119] The following day, on October 5, 2011, Apple announced that Jobs had died, marking the end of an era for Apple Inc.[120][121] The iPhone 4S was officially released on October 14, 2011.
#On October 29, 2011, Apple purchased C3 Technologies, a mapping company, for $240 million, becoming the third mapping company Apple has purchased.[122] On January 10, 2012, Apple paid $500 million to acquire Anobit, an Israeli hardware company that developed and supplies a proprietary memory signal processing technology that improves the performance of flash-memory used in iPhones and iPads.[123][124]
#On January 19, 2012, Apple's Phil Schiller introduced iBooks Textbooks for iOS and iBook Author for Mac OS X in New York City.[125] This was the first major announcement by Apple since the passing of Steve Jobs, who stated in his biography that he wanted to reinvent the textbook and education. The 3rd generation iPad was announced on March 7, 2012. It includes a Retina display, a new CPU, a five megapixel camera, and 1080p video recording.[126][127]
#On July 24, 2012, during a conference call with investors, Tim Cook said that he loved India, but that Apple was going to expect larger opportunities outside of India, citing the reason as the 30% sourcing requirement from India.[128][129][130][131]
#On August 20, 2012, Apple's rising stock rose the company's value to a world-record $624 billion. This beat the non-inflation-adjusted record for market capitalization set by Microsoft in 1999.[132] On August 24, 2012, a US jury ruled that Samsung should pay Apple $1.05 billion (£665m) in damages in an intellectual property lawsuit. Samsung said they will appeal the court ruling.[133] Samsung subsequently prevailed on its motion to vacate this damages award, which the Court reduced by $450 million.[134] The Court further granted Samsung's request for a new trial.[134]
#On September 12, 2012, Apple unveiled the iPhone 5, featuring an enlarged screen, more powerful processors, and running iOS 6. The latter includes a new mapping application (replacing Google Maps) that has attracted some criticism.[135] It was made available on September 21, 2012, and became Apple's biggest iPhone launch, with over 2 million pre-orders pushing back the delivery date to late October.[136]
#On October 23, 2012, Apple unveiled the iPad Mini, which features a 7.9-inch screen in contrast to the iPad's 9.7-inch screen. Apple also released a third-generation 13-inch MacBook Pro with a Retina display; the iPad 4, featuring a faster processor and a Lightning dock connector;[137][137] and new iMac and Mac Mini computers.[138][139] After the launch of Apple's iPad Mini and fourth generation iPad on November 3, 2012, Apple announced that they had sold 3 million iPads in three days of the launch, but it did not mention the sales figures of specific iPad models.[140]
#n November 10, 2012, Apple confirmed a global settlement that would dismiss all lawsuits between Apple and HTC up to that date, in favor of a ten-year license agreement for current and future patents between the two companies.[141] It is predicted that Apple will make $280 million a year from this deal with HTC.[142]
#In December 2012, in a TV interview for NBC's Rock Center and also aired on the Today morning show, Apple CEO Tim Cook said that in 2013 the company will produce one of its existing lines of Mac computers in the United States.[143] In January 2013, Cook stated that he expected China to overtake the US as Apple's biggest market.[144]
#In March 2013, Apple announced a patent for an augmented reality (AR) system that can identify objects in a live video stream and present information corresponding to these objects through a computer-generated information layer overlaid on top of the real-world image.[145]
#At the Worldwide Developer's Conference on June 10, 2013, Apple announced the seventh iOS operating system alongside OS X Mavericks, the tenth version of Mac OS X, and a new Internet radio service called iTunes Radio.[146][147][148] iOS 7 and OS X Mavericks are both expected to be released during fall 2013,[146][147] while the iTunes Radio Service, which will be integrated with Apple's personal voice-assistant software program Siri, is scheduled for release in the second half of 2013. The radio service features more than 200 stations according to company's statement.[149][150]
#On July 2, 2013, Apple announced the recruitment of Paul Deneve, Belgian President and CEO of Yves Saint Laurent, to Apple's top ranks. A spokesperson for the company stated, "We're thrilled to welcome Paul Deneve to Apple. He'll be working on special projects as a vice president reporting directly to Tim Cook."[151]
#   Alongside Google vice-president Vint Cerf and AT&T CEO Randall Stephenson, Cook attended a closed-door summit held by President Obama on August 8, 2013 in regard to government surveillance and the Internet in the wake of the Edward Snowden NSA incident.[152][153]
#A report on August 22, 2013 confirmed that Apple acquired Embark Inc., a small Silicon Valley-based mapping company. Embark builds free transit apps to help smartphone users navigate public transportation in U.S. cities such as New York, San Francisco and Chicago. Following the confirmation of the acquisition, an Apple spokesperson explained, "Apple buys smaller technology companies from time to time, and we generally do not discuss our purpose or plans." In November 2012, Embark claimed that over 500,000 people used its apps.[154]
#An anonymous Apple employee revealed to the Bloomberg media publication that the opening of a Tokyo, Japan store is planned for 2014. The construction of the store will be completed in February 2014, but as of August 29, 2013, Takashi Takebayashi, a Tokyo-based spokesman for Apple, has not made any comment to the media. A Japanese analyst has stated, "For Apple, the Japanese market is appealing in terms of quantity and price. There is room to expand tablet sales and a possibility the Japanese market expands if Apple’s mobile carrier partners increase.[155]
#On October 1, 2013, Apple India executives unveiled a plan to expand further into the Indian market, following Cook's acknowledgment of the country in July 2013 when sales results showed that iPhone sales in India grew 400% during the second quarter of 2013. In attendance at the confidential meeting were 20 CEOs and senior executives from telecom and electronic retail companies.[156]
#In response to the July 2013 death of a Chinese woman, who was found electrocuted holding an iPhone that was recharging with a non-Apple charger, and a similar incident (also in July 2013) that left a Chinese citizen in a coma, Apple announced a program whereby authorized Apple outlets will receive any iPhone, iPod, or iPad chargers not made by Apple in exchange for the sale of an Apple charger for US$10—half the usual retail price.[157]
#See also: Timeline of Macintosh models, List of Macintosh models grouped by CPU type, and List of Macintosh models by case type
#MacBook Air: Consumer ultra-thin, ultra-portable notebook, introduced in 2008.
#MacBook Pro: Professional notebook, introduced in 2006.
#ac Mini: Consumer sub-desktop computer and server, introduced in 2005.
#iMac: Consumer all-in one desktop computer, introduced in 1998.
#Mac Pro: Workstation desktop computer, introduced in 2006.
#Apple sells a variety of computer accessories for Macs, including Thunderbolt Display, Magic Mouse, Magic Trackpad, Wireless Keyboard, Battery Charger, the AirPort wireless networking products, and Time Capsule.
#On January 27, 2010, Apple introduced their much-anticipated media tablet, the iPad, running a modified version of iOS. It offers multi-touch interaction with multimedia formats including newspapers, magazines, ebooks, textbooks, photos, movies, videos of TV shows, music, word processing documents, spreadsheets, videogames, and most existing iPhone apps.[158] It also includes a mobile version of Safari for web browsing, as well as access to the App Store, iTunes Library, iBookstore, contacts, and notepad. Content is downloadable via Wi-Fi and optional 3G service or synced through the user's computer.[159] AT&T was initially the sole US provider of 3G wireless access for the iPad.[160]
#On March 2, 2011, Apple introduced the iPad 2, which had a faster processor and a camera on the front and back. It also added support for optional 3G service provided by Verizon in addition to the existing offering by AT&T.[161] However, the availability of the iPad 2 has been limited as a result of the devastating earthquake and ensuing tsunami in Japan in March 2011.[162]
#On March 7, 2012, Apple introduced the third-generation iPad, marketed as "the new iPad". It added LTE service from AT&T or Verizon, the upgraded A5X processor, and the Retina display (2048 by 1536 resolution), originally implemented on the iPhone 4 and iPhone 4S. The dimensions and form factor remained relatively unchanged, with the new iPad being a fraction thicker and heavier than the previous version, and minor positioning changes.[163]
#On October 23, 2012, Apple's fourth-generation iPad came out, marketed as the "iPad with Retina display". It added the upgraded A6X processor and replaced the traditional 30-pin dock connector with the all-digital Lightning connector.[164] The iPad Mini was also introduced, with a reduced 7.9-inch display and featuring much of the same internal specifications as the iPad 2.[165]
#Since its launch, iPad[166] users have downloaded three billion apps, while the total number of App Store downloads is over 25 billion.[167]
#on October 23, 2001, Apple introduced the iPod digital music player. Several updated models have since been introduced, and the iPod brand is now the market leader in portable music players by a significant margin, with more than 350 million units shipped as of September 2012.[168] Apple has partnered with Nike to offer the Nike+iPod Sports Kit, enabling runners to synchronize and monitor their runs with iTunes and the Nike+ website.
#Apple currently sells four variants of the iPod:
#iPod Shuffle: Ultra-portable digital audio player, currently available in a 2 GB model, introduced in 2005.
#iPod Nano: Portable media player, currently available in a 16 GB model, introduced in 2005. Earlier models featured the traditional iPod click wheel, though the current generation features a multi-touch interface and includes an FM radio and a pedometer.
#iPod Touch: Portable media player than runs iOS, currently available in 32 and 64 GB models, introduced in 2007. The current generation features the Apple A5 processor, a Retina display, and dual cameras on the front (1.2 megapixel sensor) and back (5 megapixel iSight), the latter of which supports HD video recording at 1080p.[169]
#iPod Classic: Portable media player, currently available in a 160 GB model, first introduced in 2001.[170]
#At the Macworld Conference & Expo in January 2007, Steve Jobs introduced the long-anticipated[171] iPhone, a convergence of an Internet-enabled smartphone and iPod.[172] The original iPhone was released on June 29, 2007 for $499 (4 GB) and $599 (8 GB) with an AT&T contract.[173] On February 5, 2008, it was updated to have 16 GB of memory, in addition to the 8 GB and 4 GB models.[174] It combined a 2.5G quad band GSM and EDGE cellular phone with features found in handheld devices, running scaled-down versions of Apple's Mac OS X (dubbed iPhone OS, later renamed iOS), with various Mac OS X applications such as Safari and Mail. It also includes web-based and Dashboard apps such as Google Maps and Weather. The iPhone features a 3.5-inch (89 mm) touchscreen display, Bluetooth, and Wi-Fi (both "b" and "g").[172]
#At Worldwide Developers Conference (WWDC) on June 9, 2008, Apple announced the iPhone 3G. It was released on July 11, 2008, with a reduced price of $199 for the 8 GB version, and $299 for the 16 GB version.[175] This version added support for 3G networking and assisted-GPS navigation. The flat silver back and large antenna square of the original model were eliminated in favor of a curved glossy black or white back. Following customer complaints, the previously-recessed headphone jack was changed to a flush jack for compatibility with more styles of headphones. Software capabilities were improved with the release of the App Store, providing applications for download that were compatible with the iPhone. On April 24, 2009, the App Store [176] surpassed one billion downloads.[177] At WWDC on June 8, 2009, Apple announced the iPhone 3GS. It provided an incremental update to the device, including faster internal components, support for faster 3G speeds, video recording capbility, and voice control.
#at WWDC on June 7, 2010, Apple announced the iPhone 4, which the company describes as the "biggest leap we've taken" since the original model.[178] It features an all-new design, a 960x640 display, the Apple A4 processor also used in the iPad, a gyroscope for enhanced gaming, 5MP camera with LED flash, front-facing VGA camera and FaceTime video calling. Shortly after its release, reception issues were discovered by consumers, due to the stainless steel band around the edge of the device, which also serves as the phone's cellular signal and Wi-Fi antenna. The issue was corrected by a "Bumper Case" distributed by Apple for free to all owners for a few months. In June 2011, Apple overtook Nokia to become the world's biggest smartphone maker by volume.[179]
#On October 4, 2011, Apple unveiled the iPhone 4S, which was released in the United States, Canada, Australia, United Kingdom, France, Germany, and Japan on October 14, 2011, with other countries set to follow later in the year.[180] It features the Apple A5 processor, and is the first model offered by Sprint (joining AT&T and Verizon Wireless as the United States carriers offering iPhone models). On October 19, 2011, Apple announced an agreement with C Spire Wireless to sell the iPhone 4S with that carrier in the near future, marking the first time the iPhone was officially supported on a regional carrier's network.[181] Another notable feature of the iPhone 4S was Siri voice assistant technology, which Apple had acquired in 2010,[182] as well as other features, including an updated 8MP camera with new optics. Apple sold 4 million iPhone 4S phones in the first three days of availability, making it the most successful launch of any mobile phone to date.[183]
#On September 12, 2012, Apple introduced the sixth-generation iPhone,[184] the iPhone 5. It added a 4-inch display, 4G LTE connectivity, and the upgraded Apple A6 chip, among several other improvements.[185] Two million iPhones were sold in the first twenty-four hours of pre-ordering[186] and over five million handsets were sold in the first three days of its launch.[187]
#A patent filed by the corporation, published in late July 2013, revealed the development of a new iPhone battery system that uses location data in combination with data on the user's habits to moderate the handsets power settings accordingly. Apple is working towards a power management system that will provide features such as the ability of the iPhone to estimate the length of time a user will be away from a power source to modify energy usage and a detection function that adjusts the charging rate to best suit the type of power source that is being used.[188]
#A#Media reports emerged in early August that announced that Apple would be launching its next iPhone model on September 10, 2013, but further details were not available. Brian Barrett, Managing Editor of the Gizmodo publication, speculated that either an upgraded version of the iPhone 5 or a budget version will be released.[189]
# Apple announced on September 1, 2013 that its iPhone trade-on program would be implemented at all of its 250 specialty stored in the US. For the program to become available, customers must have a valid contract, and must purchase a new phone, rather than simply receive credit to be used at a later date. A significant part of the program's goal is to increase the number of customers who purchase iPhones at Apple stores rather than carrier stores.[190]
#Upon the launch of the iPhone 5S and iPhone 5C, Apple sold over nine million devices in the first three days of its launch, which sets a new record for first weekend smartphone sales.[191] This was the first time that Apple has simultaneously launched two models and the inclusion of China in the list of markets contributed to the record sales result.[192]
#At the 2007 Macworld conference, Jobs demonstrated the Apple TV, (previously known as the iTV),[193] a set-top video device intended to bridge the sale of content from iTunes with high-definition televisions. The device links up to a user's TV and syncs, either via Wi-Fi or a wired network, with one computer's iTunes library and streams from an additional four. The Apple TV originally incorporated a 40 GB hard drive for storage, includes outputs for HDMI and component video, and plays video at a maximum resolution of 720p.[194] On May 31, 2007 a 160 GB drive was released alongside the existing 40 GB model[195] and on January 15, 2008 a software update was released, which allowed media to be purchased directly from the Apple TV.[196]
#In September 2009, Apple discontinued the original 40 GB Apple TV and now continues to produce and sell the 160 GB Apple TV. On September 1, 2010, alongside the release of the new line of iPod devices for the year, Apple released a completely redesigned Apple TV. The new device is 1/4 the size, runs quieter, and replaces the need for a hard drive with media streaming from any iTunes library on the network along with 8 GB of flash memory to cache media downloaded. Apple with the Apple TV has added another device to its portfolio that runs on its A4 processor along with the iPad and the iPhone. The memory included in the device is the half of the iPhone 4 at 256 MB; the same as the iPad, iPhone 3GS, third- and fourth-generation iPod Touch.[197]
#It has HDMI out as the only video out source. Features include access to the iTunes Store to rent movies and TV shows (purchasing has been discontinued), streaming from internet video sources, including YouTube and Netflix, and media streaming from an iTunes library. Apple also reduced the price of the device to $99. A third generation of the device was introduced at an Apple event on March 7, 2012, with new features such as higher resolution (1080p) and a new user interface.
#Apple develops its own operating system to run on Macs, OS X, the latest version being OS X Mountain Lion (version 10.8). Apple also independently develops computer software titles for its OS X operating system. Much of the software Apple develops is bundled with its computers. An example of this is the consumer-oriented iLife software package that bundles iMovie, iPhoto and GarageBand. For presentation, page layout and word processing, iWork is available, which includes Keynote, Pages, and Numbers. iTunes, QuickTime media player, and Software Update are available as free downloads for both OS X and Windows.
#Apple also offers a range of professional software titles. Their range of server software includes the operating system OS X Server; Apple Remote Desktop, a remote systems management application; and Xsan, a Storage Area Network file system. For the professional creative market, there is Aperture for professional RAW-format photo processing; Final Cut Pro, a video production suite; Logic Pro, a comprehensive music toolkit; and Motion, an advanced effects composition program.
#@Apple also offers online services with iCloud, which provides cloud storage and syncing for a wide range of data, including email, contacts, calendars, photos and documents. It also offers iOS device backup, and is able to integrate directly with third-party apps for even greater functionality. iCloud is the fourth generation of online services provided by Apple, and was preceded by MobileMe, .Mac and iTools, all which met varying degrees of success
a = input()
print(a)